### ISSUE TITLE
Pagination order is almost right

### ISSUE THREAD

**Issue by heisler98** [tiberloop/flaskchat#40]
Message pagination order at the endpoint `/rooms/<id>/messages` is almost right. The earliest message is at the bottom of the array sent in page 1. The latest message is at the top of page (msgCount / 50). Ideally, the earliest message is at the bottom of the array on page (msgCount / 50), and the latest message is at the top of the array on page 1. 

My suspicion is that reversal is happening, but it's happening per page, not per collection of room messages.

**Comment by colingoodman** [comment]
Linking this for later
https://www.codementor.io/@arpitbhayani/fast-and-efficient-pagination-in-mongodb-9095flbqr

**Comment by colingoodman** [comment]
https://www.mongodb.com/blog/post/paging-with-the-bucket-pattern--part-1

**Comment by colingoodman** [comment]
Buckets
