### ISSUE TITLE
avatar_id in message is copied, not referenced

### ISSUE THREAD

**Issue by heisler98** [tiberloop/flaskchat#69]
A message object has an `avatar_id` field (which is so very useful). Unfortunately, this value is copied and not referenced to a particular user object. When a user changes their avatar, or worse, when the server deletes an old avatar, this ID field is then useless. 

e.g. Here's a message sent by colingoodman in general: 
```
{
                    "avatar_id": "60f8790f1f833f812fc01cf0",
                    "image_id": "None",
                    "text": "51",
                    "time_sent": 1626907056.7369473,
                    "user_id": "60ec6b28751e3f5bd5bec4cd",
                    "username": "colingoodman"
}
```

Here's colingoodman's current avatar ID, in `users/list`:
`60f9c97ca715044b0a2e4535`

The `avatar_id` field is rendered useless without some sort of referencing.

**Comment by heisler98** [comment]
FYI – asking the server for the old avatar returns the following:
```
{
    "I could not find the requested file": "60f8790f1f833f812fc01cf0"
}
```

**Comment by colingoodman** [comment]
After our discussion I am no longer going to return avatar_id with messages, the clients will be responsible for using the most up to date avatar as per what is sent via the users endpoints or via socket updates.
